name: "Roslyn analyzers → SARIF (Windows runner)"

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  roslyn-sarif:
    runs-on: [self-hosted, windows, x64]
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore (SDK-style)
        run: dotnet restore "TestA.sln"
        shell: powershell

      - name: Build and emit SARIF
        id: build
        run: |
          New-Item -ItemType Directory -Path "$env:GITHUB_WORKSPACE\reports" -Force | Out-Null
          # Use msbuild for full .NET Framework solutions; OR use dotnet build for SDK-style:
          # msbuild "TestA.sln" /t:Rebuild /p:Configuration=Release /p:RunAnalyzers=true /p:ErrorLog="$env:GITHUB_WORKSPACE\reports\roslyn-report.sarif"
          # dotnet option (uncomment if you prefer):
          dotnet build "TestA.sln" -c Release -p:RunAnalyzers=true -p:ErrorLog="$env:GITHUB_WORKSPACE/reports/roslyn-report.sarif"
        shell: powershell
        continue-on-error: true

      - name: Check for SARIF file
        id: check
        run: |
          if (Test-Path "$env:GITHUB_WORKSPACE\reports\roslyn-report.sarif") {
            "sarif_exists=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          } else {
            "sarif_exists=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }
        shell: powershell

      - name: Upload SARIF to GitHub (Code scanning)
        if: steps.check.outputs.sarif_exists == 'true'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/roslyn-report.sarif
